"""initial schema

Revision ID: 41fa60f16fd8
Revises: 
Create Date: 2026-04-19 15:36:50.876922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41fa60f16fd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('profile_type', sa.String(length=32), nullable=False),
    sa.Column('is_prosumer', sa.Boolean(), nullable=False),
    sa.Column('solar_kwp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('energy_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('generation_kwh', sa.Float(), nullable=False),
    sa.Column('net_grid_flow', sa.Float(), nullable=False),
    sa.Column('meter_import_kwh', sa.Float(), nullable=False),
    sa.Column('meter_export_kwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timestamp', name='uq_user_timestamp')
    )
    op.create_index(op.f('ix_energy_records_user_id'), 'energy_records', ['user_id'], unique=False)
    op.create_index('ix_records_ts', 'energy_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_ts', table_name='energy_records')
    op.drop_index(op.f('ix_energy_records_user_id'), table_name='energy_records')
    op.drop_table('energy_records')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
